export * from './authentication.graphql'
export * from './viewsinglerisk.graphql'
export * from './viewallrisks.graphql'
export * from './viewrisks.graphql'
export * from './createrisktype.graphql'
export * from './createsinglerisk.graphql'
export * from './riskpicklist.graphql'
